---
# From https://github.com/gitlabhq/gitlabhq/blob/6-1-stable/doc/install/installation.md
# 1. Packages / Dependencies
- hosts: gitlab
  sudo: yes
  tasks:
    - name: ensure apt cache is up to date
      action: apt update_cache=yes
    - name: ensure app apt dependencies are installed
      action: apt pkg=$item
      with_items:
      - build-essential
      - zlib1g-dev
      - libyaml-dev
      - libssl-dev
      - libgdbm-dev
      - libreadline-dev
      - libncurses5-dev
      - libffi-dev
      - curl
      - git-core
      - redis-server
      - checkinstall
      - libxml2-dev
      - libxslt1-dev
      - libcurl4-openssl-dev
      - libicu-dev
      - python-docutils

- hosts: gitlab
  sudo: yes
  tasks:
    - name: ensure /usr/local/bin/python2 links to /usr/bin/python
      file: state=link src=/usr/bin/python path=/usr/local/bin/python2

# 2. Ruby

- hosts: gitlab
  sudo: no
  vars:
    url: ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p247.tar.gz
    path: /tmp/ruby/ruby-2.0.0-p247
  tasks:
    - name: ensure directory /tmp/ruby is present
      file: state=directory path=/tmp/ruby
    - name: ensure ruby is downloaded
      get_url: url=$url dest=/tmp/ruby
    - name: ensure ruby is extracted
      command: tar -xf ruby-2.0.0-p247.tar.gz chdir=/tmp/ruby creates=$path
    - name: ensure ruby is configured
      command: ./configure chdir=$path creates=$path/Makefile
    - name: ensure ruby is compiled
      command: make chdir=$path creates=$path/ruby

- hosts: gitlab
  sudo: yes
  vars:
    path: /tmp/ruby/ruby-2.0.0-p247
  tasks:
    - name: ensure ruby is installed
      command: make install chdir=$path creates=/usr/local/bin/ruby
    - name: ensure bundler is installed
      command: gem install bundler --no-ri --no-rdoc creates=/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.3.0


# 3. System Users
- hosts: gitlab
  sudo: yes
  tasks:
    - name: ensure user git is present
      user: state=present name=git system=yes shell=/bin/sh comment="Git Version Control"

# 4. GitLab shell
- hosts: gitlab
  sudo: yes
  sudo_user: git
  vars_files:
    - vars.yml
  tasks:
    - name: ensure Gitlab-Shell git repository is cloned
      git: repo=https://github.com/gitlabhq/gitlab-shell.git dest=/home/git/gitlab-shell version=v1.5.0
    - name: ensure gitlab-shell config is written
      action: template src=templates/gitlab_shell_config.yml.tmpl dest=/home/git/gitlab-shell/config.yml mode=0755
    - name: ensure gitlab-shell is installed
      command: /home/git/gitlab-shell/bin/install